config/routes.rb
Lostandfound::Application.routes.draw do
  resources :items do
    collection do
      get 'search'
      get 'do_search'
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :type

	#Searches for the list of matching items based on query inputs
	def self.search(title, connector1, description, connector2, owner, connector3, type)
			if title != "" and description != ""
				self.where("title LIKE ? #{connector1} description LIKE ? #{connector2} owner LIKE ? #{connector3} type_id = ?",
				 '%'+title+'%', '%'+description+'%', owner, type).to_a
			elsif title != ""
				self.where("title LIKE ? #{connector2} owner LIKE ? #{connector3} type_id = ?",
				 '%'+title+'%', owner, type).to_a
			else
				self.where("description LIKE ? #{connector2} owner LIKE ? #{connector3} type_id = ?",
				 '%'+description+'%', owner, type).to_a
			end
	end
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # GET /items/search
  def search
    types = Type.all
    @type_drop_down = [[]]
    types.each do |t|
      @type_drop_down << [t.title, t.id]
    end
    @and_or = [['OR', 'OR'],['AND', 'AND']]
  end

  # GET /items/do_search(params)
  def do_search
    @items = Item.search(params[:title], params[:connector1], params[:description], 
      params[:connector2], params[:owner], params[:connector3], params[:t][:t_id])
    if @items != nil
      render :index
    else
      redirect_to search_items_path
    end
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<!DOCTYPE html>
<html>
<head>
 <link rel="stylesheet" href="/app/assets/stylesheets/application.css"
 </head>
<h1>Items:</h1>
<div id="search">
<%= link_to 'Search', search_items_path %>
</div>
<table id="item_table">
  <thead id="categories">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Owner</th>
      <th>Type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody id="item_list">
    <% @items.each do |item| %>
      <tr>
        <td id="title"><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.owner %></td>
        <td><%= item.type.title %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>
</html>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
<body>
<h1>Search</h1>

<div id="homelink"><%= link_to 'Home', items_path %></div>

<%= form_tag(do_search_items_path, method: "get") do %>
	<%= label_tag(:title, "Title:") %></br>
	<%= text_field_tag(:title) %>
	<%= select_tag(:connector1, options_for_select(@and_or)) %></br>
	<%= label_tag(:description, "Description:") %></br>
	<%= text_field_tag(:description) %>
	<%= select_tag(:connector2, options_for_select(@and_or)) %></br>
	<%= label_tag(:owner, "Owner:") %></br>
	<%= text_field_tag(:owner) %>
	<%= select_tag(:connector3, options_for_select(@and_or)) %></br>
	<%= label_tag(:t, "Type:") %></br>
	<%= select(:t, :t_id, @type_drop_down)%>
	<%= submit_tag("Search") %>
<% end %>
</body>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @item.type %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lostandfound</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="/app/assets/stylesheets/application.css"
  <script src="https://code.jquery.com/jquery.js"></script>

</head>
<body>
<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>

<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>

</body>
</html>